apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8089
    protocol: TCP
    name: web
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: rpc
  - port: 5558
    targetPort: 5558
    protocol: TCP
    name: rpc2
  selector:
    app: locust
    role: master